# Generated by Django 5.0.6 on 2024-05-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
